// permission-role.map.ts
export const ROLE_PERMISSION_MAP: {
  [roleName: string]: {
    method?: string;
    module?: string;
    apiPath?: string;
  }[];
} = {
  CUSTOMER_ROLE: [
    { method: 'POST', apiPath: '/appointments/' },
    { method: 'GET', apiPath: '/appointments/findOne/:id' },
    { method: 'GET', apiPath: '/appointments/patienttoken' },
    { method: 'PATCH', apiPath: '/patients/:id' },
    { method: 'POST', apiPath: '/patients/by-token' },
    { method: 'POST', apiPath: '/payments/vnpay-url' },
    { method: 'POST', apiPath: '/payments/wallet' },
    { method: 'GET', apiPath: '/treatments/:id' },
  ],
  STAFF_ROLE: [
    { method: 'GET', apiPath: '/appointments/' },
    { method: 'PATCH', apiPath: '/appointments/:id/confirm' },
    { method: 'PATCH', apiPath: '/appointments/:id' },
    { method: 'DELETE', apiPath: '/appointments/:id' },
    { method: 'GET', apiPath: '/appointments/findOne/:id' },
    { method: 'GET', apiPath: '/appointments/by-date-range' },
    { method: 'POST', apiPath: '/appointments/cancle' },
    { method: 'POST', apiPath: '/appointments/cancle/doctor' },
    { method: 'POST', apiPath: '/medicalrecords/' },
    { method: 'POST', apiPath: '/medicalrecords/:personalId' },
    { method: 'GET', apiPath: '/medicalrecords/getone/:id' },
    { method: 'GET', apiPath: '/medicalrecords/personalID' },
    { method: 'PUT', apiPath: '/medicalrecords/:id' },
    { method: 'GET', apiPath: '/patients/' },
    { method: 'GET', apiPath: '/patients/:id' },
    { method: 'PATCH', apiPath: '/patients/:id' },
    { method: 'POST', apiPath: '/patients/by-personal-id' },
    { method: 'GET', apiPath: '/prescribedRegiments/' },
    { method: 'GET', apiPath: '/prescribedRegiments/:id' },
    { method: 'GET', apiPath: '/treatments/' },
    { method: 'GET', apiPath: '/treatments/:id' },
  ],
  MANAGER_ROLE: [
    { method: 'GET', apiPath: '/appointments/' },
    { method: 'POST', apiPath: '/appointments/cancle' },
    { method: 'POST', apiPath: '/appointments/cancle/doctor' },
    { method: 'POST', apiPath: '/drugs/' },
    { method: 'PATCH', apiPath: '/drugs/:id' },
    { method: 'DELETE', apiPath: '/drugs/:id' },
    { method: 'POST', apiPath: '/regiments/' },
    { method: 'PATCH', apiPath: '/regiments/:id' },
    { method: 'DELETE', apiPath: '/regiments/:id' },
    { method: 'POST', apiPath: '/doctor-schedules/' },
    { method: 'GET', apiPath: '/doctor-schedules/' },
    { method: 'GET', apiPath: '/doctor-schedules/:doctorId/schedule-by-week' },
    { method: 'PATCH', apiPath: '/doctor-schedules/:id' },
    { method: 'DELETE', apiPath: '/doctor-schedules/:id' },
    { method: 'GET', apiPath: '/medicalrecords/' },
    { method: 'PUT', apiPath: '/medicalrecords/:id' },
    { method: 'DELETE', apiPath: '/medicalrecords/:id' },
    { method: 'DELETE', apiPath: '/patients/:id' },
    { method: 'DELETE', apiPath: '/prescribedRegiments/:id' },
    { method: 'POST', apiPath: '/services/' },
    { method: 'PATCH', apiPath: '/services/:id' },
    { method: 'DELETE', apiPath: '/services/:id' },
    { method: 'GET', apiPath: '/treatments/' },
    { method: 'GET', apiPath: '/treatments/:id' },
    { method: 'POST', apiPath: '/doctors/' },
    { method: 'PATCH', apiPath: '/doctors/:id' },
    { method: 'DELETE', apiPath: '/doctors/:id' },
    { method: 'PATCH', apiPath: '/doctorSlots/:id' },
    { method: 'DELETE', apiPath: '/doctorSlots/:id' },
  ],
  DOCTOR_ROLE: [
    { method: 'GET', apiPath: '/appointments/by-doctor/:doctorId' },
    { method: 'POST', apiPath: '/appointments/token' },
    { method: 'GET', apiPath: '/appointments/findOne/:id' },
    { method: 'POST', apiPath: '/medicalrecords/' },
    { method: 'POST', apiPath: '/medicalrecords/:personalId' },
    { method: 'GET', apiPath: '/medicalrecords/getone/:id' },
    { method: 'GET', apiPath: '/medicalrecords/personalID' },
    { method: 'POST', apiPath: '/patients/by-personal-id' },
    { method: 'GET', apiPath: '/patients/:id' },
    { method: 'POST', apiPath: '/prescribedRegiments/' },
    { method: 'POST', apiPath: '/prescribedRegiments/suggest' },
    { method: 'GET', apiPath: '/prescribedRegiments/:id' },
    { method: 'PATCH', apiPath: '/prescribedRegiments/:id' },
    { method: 'POST', apiPath: '/testResults/' },
    { method: 'GET', apiPath: '/testResults/' },
    { method: 'GET', apiPath: '/testResults/:id' },
    { method: 'PATCH', apiPath: '/testResults/:id' },
    { method: 'DELETE', apiPath: '/testResults/:id' },
    { method: 'POST', apiPath: '/treatments/' },
    { method: 'GET', apiPath: '/treatments/' },
    { method: 'GET', apiPath: '/treatments/:id' },
    { method: 'PATCH', apiPath: '/treatments/:id' },
    { method: 'DELETE', apiPath: '/treatments/:id' },
    { method: 'POST', apiPath: '/doctors/token' },
    { method: 'PATCH', apiPath: '/doctor-schedules/:id/confirm' },
    { method: 'GET', apiPath: '/doctor-schedules/schedule-by-week/token' },
  ],
  ADMIN_ROLE: [
    // Permissions Module
    { method: 'POST', apiPath: '/permissions/' },
    { method: 'GET', apiPath: '/permissions/' },
    { method: 'GET', apiPath: '/permissions/:id' },
    { method: 'PATCH', apiPath: '/permissions/:id' },
    { method: 'DELETE', apiPath: '/permissions/:id' }, // Roles Module
    { method: 'POST', apiPath: '/roles/' },
    { method: 'GET', apiPath: '/roles/' },
    { method: 'GET', apiPath: '/roles/:id' },
    { method: 'PATCH', apiPath: '/roles/:id' },
    { method: 'DELETE', apiPath: '/roles/:id' }, // Users Module
    { method: 'POST', apiPath: '/users/' },
    { method: 'GET', apiPath: '/users/' },
    { method: 'GET', apiPath: '/users/:id' },
    { method: 'PATCH', apiPath: '/users/:id' },
    { method: 'DELETE', apiPath: '/users/:id' },
  ],
};
